name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: dependency_validator
        run: dart run dependency_validator
      - name: Run tests
        run: dart test
      - name: dartdoc
        run: dartdoc --no-generate-docs
      - name: Generate coverage report
        run: |
          dart pub global activate coverage
          dart run test --coverage=./coverage
          dart pub global run coverage:format_coverage --packages=.packages --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
          flags: unittests
          env_vars: OS,DART
          fail_ci_if_error: true
          verbose: true
      - name: dart pub publish --dry-run
        run: dart pub publish --dry-run

